ARG RUBY_VERSION=3.4

FROM ruby:$RUBY_VERSION-alpine

ENV API_PATH /api
ENV BUNDLE_PATH /bundle/vendor

WORKDIR ${API_PATH}

RUN apk add --update --no-cache \
    build-base \
	git \
    postgresql-dev \
    yaml-dev

EXPOSE 3000

COPY Gemfile* ${API_PATH}

RUN bundle install

ENTRYPOINT ["bin/setup"]

CMD [ "bin/dev" ]
